### PR TITLE
Feature/iiw demo

### PR DESCRIPTION
**Pull request by Hmac512**
# This PR adds the Artichoke seed store as a SDK example

This demo will be used for IIW 2022.

### CODE REVIEW

**Review by fundthmcalculus — APPROVED** [review]
In general, lets avoid binary files in the repository, but for the purposes of this demo, a couple logo icons aren't a big deal.

**Comment by Hmac512** [comment]
> In general, lets avoid binary files in the repository, but for the purposes of this demo, a couple logo icons aren't a big deal.

I’ll clean it up before this actually gets merged. Just wanted a place for comments.

**Comment by Hmac512** [comment]
https://github.com/trinsic-id/server/issues/1207#event-7754329586

For this issue.

**Comment by Hmac512** [comment]
Moved to new repo

https://github.com/trinsic-id/okeydokey-demo

**Pull request closed without merging**
